### ISSUE TITLE
project smart houese

### ISSUE THREAD

**Issue by ablas14** [hwiguna/g33k#5]
mas orang ingonesia kan saya boleh sharing dikit ilmu nxa mas
saya bingung mau buat smart house bahan nxa dan cara nxa karena saya baru kenal arduino boleh bantu dikit mas terimakasih

**Comment by hwiguna** [comment]
I would recommend the ESP8266.
https://www.youtube.com/watch?v=MWebdJwr6ks&list=PL-xZsBalytNAFgyiDI8_lwXyeVE3R4hpx&index=20

There's also a good resource in Bahasa Indonesia:
http://geeknesia.com/projects-category/smart-home
