### ISSUE TITLE
USB relays - delay between sending commands

### ISSUE THREAD

**Issue by inez** [hwiguna/g33k#7]
Hey - wasn't sure how to reach you so decided to try through creating an issue.

I looked into your code for controlling USB Relays. I have similar code but written in C# for controlling relays from Windows machine, and I noticed that if I send 0x51 and 0x03 (for instance) nothing happens - but if I but 10 ms delay in between commands then it works. Did you run into similar issue?
Thanks!

**Comment by hwiguna** [comment]
Hi, I looked at my code and it did not have a delay, but there is a serial.println for debugging, so that probably took a few miliseconds. :-)

**Comment by inez** [comment]
Do you know if it's possible to read state from the relay?

**Comment by hwiguna** [comment]
I'm not aware of a way to "read" the relay state. It's up to us to maintain that external from the module :-(
